### PR TITLE
SMTP: More verbose server greeting error - fix #387

### LINKED ISSUE #387: misleading SMTP error message when server returns bad greeting
Incorrect exception:

               if (logger.isLoggable(Level.FINE))
               logger.fine("could not connect to host \"" +
                       host + "\", port: " + port +
                       ", response: " + r);
           throw new MessagingException(
                   "Could not connect to SMTP host: " + host +
                   ", port: " + port +
                   ", response: " + r);

https://github.com/eclipse-ee4j/javamail/blob/36b3a7f524835ae4911a6b58156e5c2a3fda8b2e/mail/src/main/java/com/sun/mail/smtp/SMTPTransport.java#L2194

Correct Exception:

		if (logger.isLoggable(Level.FINE))
		    logger.fine("got bad greeting from host \"" +
				    host + "\", port: " + port +
				    ", response: " + r);
		throw new MessagingException(
			"Got bad greeting from SMTP host: " + host +
				    ", port: " + port +
				    ", response: " + r);

https://github.com/eclipse-ee4j/javamail/blob/36b3a7f524835ae4911a6b58156e5c2a3fda8b2e/mail/src/main/java/com/sun/mail/smtp/SMTPTransport.java#L2255

I also wonder if the exception should on both cases contain lastServerResponse as well, it will be informative to see the rejection reason I guess.

### PR DESCRIPTION
**Pull request by ecki**
This will include more error information about bad smtp greetings. It will also unify two different codepath exceptions.

### CODE REVIEW

**Comment by ecki** [comment]
Is it possible to approve more than one email address for the ECA? (my github account and company address are known, the apache commiter email I used for this seems to be not associated with my profile...)

**Comment by bshannon** [comment]
> Is it possible to approve more than one email address for the ECA?

Don't know, you would need to ask Eclipse about that.

**Comment by bshannon** [comment]
Well, I see that you haven't signed the ECA, or haven't included the Signed-Off-By header in your commit ("git commit -s").
Please update your pull request so I can accept it.

**Comment by bshannon** [comment]
> Is it possible to approve more than one email address for the ECA? (my github account and company address are known, the apache commiter email I used for this seems to be not associated with my profile...)

Sorry, just saw this comment.  I don't know.  You would need to contact Eclipse for that,
but I don't think that's possible.

**Comment by ecki** [comment]
I will re-submit with different e-Mail, what kind of tweaks and Test you are looking for?

**Comment by bshannon** [comment]
lastServerResponse needs to be saved in case a QUIT command is sent on failure, which would overwrite it.

A test that checks that the expected error message is produced when a bad greeting response
is returned, and a test that checks that a different error message is produced when the connection
fails, would be useful.

**Comment by bshannon** [comment]
@ecki Are you still planning to resubmit this?  Or should I just close it?

**Comment by ecki** [comment]
Imwill resubmit this, but currently I am busy.

**Pull request closed without merging**
