### PR TITLE
javax > jakarta api change

### PR DESCRIPTION
**Pull request by ederks85**
Signed-off-by: Edwin Derks <ederks85@gmail.com>

### CODE REVIEW

**Comment by ederks85** [comment]
Hello, can somebody with knowledge of this project please assist?

1. I can't get the MailDateFormatTest to pass since there is a problem with the (de)serialization of the data used in that test (MailDateFormat_xxx.ser). How can this data be re-serialized?

2. I have renamed everything regarding the "jakarta" name change for the **mail specification only** in this pull request, so not the Activation code and all the test projects that are also present in this repo. Is it preferred to have the rest of the project renamed in separate branches and pull request, or can I continue on this branch?

Thanks!

Edwin

**Comment by bshannon** [comment]
I wish you had checked with me before starting this work...

I've already got this work done and staged in an internal repo so I'm going to have to close this PR.
Sorry.  I hope to push my changes soon.

**Comment by ederks85** [comment]
Hi Bill,

that's unfortunate for me. I didn't find any communication or Issues related to this, so I create an Issue for the name change almost a month ago. Since there hasn't been any input on that since then, I assumed nobody was working on this.

kr,

Edwin

**Comment by bshannon** [comment]
Always use the dev mailing list!

I ignored the issue because I already knew the work needed to be done and I had already done it.

**Comment by ederks85** [comment]
Hi Bill,

No problem, I will do so in the future in order to avoid similar situations.

Kr,

Edwin

**Pull request closed without merging**
