### PR TITLE
Remove dead code

### PR DESCRIPTION
**Pull request by pzygielo**

### CODE REVIEW

**Comment by bshannon** [comment]
Why was this closed?  I still planned to merge this in after EE 9.

**Comment by bshannon** [comment]
For some reason this PR can't be built,  I you can get it to build, we can integrate it.

**Comment by pzygielo** [comment]
> For some reason this PR can't be built, 

I guess - for the same that other PRs or master fail as well. - stage: mail-tck-run

> If you can get it to build

It's out of my control, I can't.

**Comment by pzygielo** [comment]
Drafted to rebase onto #452

**Comment by pzygielo** [comment]
With version 2.0.0 released - could this be merged, please?

**Comment by lukasj** [comment]
No, not yet. Availability of the tag != release. Or do you see it maven central?

**Comment by pzygielo** [comment]
Thanks for checking @lukasj.

> No, not yet. Availability of the tag != release. 

True, as 2.0.0 tag was moved around already.

> Or do you see it maven central?

I've only seen https://github.com/jakartaee/specifications/pull/247 and [good news of happy integration of j-mail into glassfish](https://github.com/eclipse-ee4j/glassfish/pull/23175).
But indeed - [final version 2 is not published yet](https://repo.maven.apache.org/maven2/jakarta/mail/jakarta.mail-api).

**Comment by lukasj** [comment]
GlassFish is consuming artifacts from staging repo (https://jakarta.oss.sonatype.org/) in order to test them in wider context. Artifacts are also needed for formal steps (like various reviews, ballots) to start. During this period, it may happen that the tag gets changed, as you noticed with mail (even though, from technical point of view, this could be avoided)

**Comment by pzygielo** [comment]
> Or do you see it maven central?

Yes, now I do.

**Pull request closed without merging**
