### PR TITLE
Moving CHANGES.txt from angus-mail

### PR DESCRIPTION
**Pull request by jbescos**
CHANGES.txt was moved from mail to angus-mail, but the versions does not match with angus-mail.

I think this CHANGES.txt should stay here, and we can add a new CHANGES.txt in angus-mail.

### CODE REVIEW

**Review by lukasj — COMMENTED** [review]
add a note that in 2.1.0, the implementation has been removed  and new one - the angus project - has been created based on that (...just use some better wording, please)

**Comment by lukasj** [comment]
can you add a section about 2.1.1 and missing entries there so we can merge/close this, please?

**Comment by jbescos** [comment]
> can you add a section about 2.1.1 and missing entries there so we can merge/close this, please?

Done

**Review by lukasj — APPROVED** [review]
LGTM

**Pull request merged**
