### PR TITLE
expected resource not found: /META-INF/javamail.default.address.map #598

### PR DESCRIPTION
**Pull request by jbescos**
https://github.com/eclipse-ee4j/mail/issues/598

### CODE REVIEW

**Comment by jbescos** [comment]
This is the error. It looks it is not compiling in the correct path.

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.200 s
[INFO] Finished at: 2022-04-02T06:28:44Z
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "staging" could not be activated because it does not exist.
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/home/jenkins/agent/workspace/mail_PR-599). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException
```

**Review by lukasj — COMMENTED** [review]
put a note to changes, please

**Comment by jbescos** [comment]
> put a note to changes, please

Done

**Review by lukasj — APPROVED** [review]
LGTM

**Pull request merged**
