### PR TITLE
Fix : Throwing Exception without lastServerResponse [401]

### PR DESCRIPTION
**Pull request by sarathkumar-raja**
Creating this pull request for the issue : https://github.com/eclipse-ee4j/mail/issues/401

### CODE REVIEW

**Comment by bshannon** [comment]
This duplicates PR #388 submitted by @ecki, are you the same person?
This PR doesn't address most of the issues with that PR.  In particular,
the ECA check is still failing, and there's no test case included.

**Comment by sarathkumar-raja** [comment]
I'm not the same person.

We are using javax mail api 1.6.2 , and ran into the issue of not getting the full server response ,rather getting only the SMTP return code.

Checked the current version is also having the same issue.

Regarding ECA , it's checking my old email address, how to verify my new email address?

And let me add the test cases.

**Comment by bshannon** [comment]
The issues with the Pull Request haven't been resolved.
I'm just going to fix this issue myself in the next few days
unless this PR is ready.

**Comment by bshannon** [comment]
Closing this PR so I can fix it myself.

**Pull request closed without merging**
